### ISSUE TITLE
HTTP-Server templates are missing from pip installation

### ISSUE THREAD

**Issue by curufinwe** [rwth-i6/sisyphus#109]
In my singularity container I installed sisyphus via pip (directly from github). But the templates seem to be excluded, i.e. I get:
```ls: cannot access '/usr/local/lib/python3.8/dist-packages/sisyphus/templates': No such file or directory```

This results in:
```[2022-10-06 10:38:10,482] ERROR: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/sisyphus/http_server.py", line 78, in decorated_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/sisyphus/http_server.py", line 108, in output_view
    return render_template("outputs.html", outputs=outputs)
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: outputs.html```

**Comment by critias** [comment]
Should be resolved with https://github.com/rwth-i6/sisyphus/commit/e35c2bb015d74a9af63fa4c27757688a07e0ccc4
