### ISSUE TITLE
Local job hangs, not available input

### ISSUE THREAD

**Issue by albertz** [rwth-i6/sisyphus#171]
Due to a bug in my setup, a `ReturnnTrainingJob` incorrectly got into finished state, although it was not fully finished.

Then a recognition job (`ReturnnForwardJobV2`) was started, depending on a model checkpoint which does not exist. Specifically:
```
$ cat work/i6_core/returnn/forward/ReturnnForwardJobV2.5HnzBAbfw22G/info
INPUT: /u/zeyer/setups/combined/2021-05-31/work/i6_core/text/label/subword_nmt/train/ReturnnTrainBpeJob.vTq56NZ8STWt/output/bpe.codes
INPUT: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11
INPUT: /u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/oggzip/BlissToOggZipJob.NSdIHfk1iw2M/output/out.ogg.zip
INPUT: /u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.por8G6TNlO9E/output/models/epoch.1280.pt
INPUT: /u/zeyer/setups/combined/2021-05-31/tools/returnn
INPUT: /u/zeyer/setups/combined/2021-05-31/work/i6_core/text/label/subword_nmt/train/ReturnnTrainBpeJob.vTq56NZ8STWt/output/bpe.vocab
PARAMETER: model_checkpoint: /u/zeyer/setups/combined/2021-05-31/work/i6_core/returnn/training/ReturnnTrainingJob.por8G6TNlO9E/output/models/epoch.1280.pt
PARAMETER: returnn_config: <i6_core.returnn.config.ReturnnConfig object at 0x7f1bca00c450>
PARAMETER: output_files: ['output.py.gz']
PARAMETER: returnn_python_exe: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11
PARAMETER: returnn_root: /u/zeyer/setups/combined/2021-05-31/tools/returnn
PARAMETER: mem_rqmt: 6
PARAMETER: log_verbosity: 5
PARAMETER: device: gpu
PARAMETER: time_rqmt: 4
PARAMETER: cpu_rqmt: 2
```
And that file `ReturnnTrainingJob.por8G6TNlO9E/output/models/epoch.1280.pt` does not exist. But because the training job finished, it started that recog job anyway.

Due to our recent change, that should have printed an error, that the input file does not exist, and then exit. However, for some reason, it just hangs?

```
$ py-spy dump -p 4115140
Process 4115140: /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11 ./sis worker --engine short work/i6_core/returnn/forward/ReturnnForwardJobV2.5HnzBAbfw22G create_files 1 --redirect_output
Python v3.11.2 (/work/tools/users/zeyer/linuxbrew/Cellar/python@3.11/3.11.2_1/bin/python3.11)

Thread 4115140 (idle): "MainThread"
    _try_wait (subprocess.py:1955)
    _wait (subprocess.py:1997)
    wait (subprocess.py:1262)
    call (subprocess.py:391)
    check_call (subprocess.py:408)
    worker_helper (sisyphus/worker.py:207)
    worker (sisyphus/worker.py:168) 
    main (sisyphus/__main__.py:234)
    <module> (sis:14)
```
and that waits for this proc:
```
$ py-spy dump -p 4115141
Process 4115141: python3 ./sis worker --engine short work/i6_core/returnn/forward/ReturnnForwardJobV2.5HnzBAbfw22G create_files 1
Python v3.11.2 (/work/tools/users/zeyer/linuxbrew/Cellar/python@3.11/3.11.2_1/bin/python3.11)

Thread 4115141 (idle): "MainThread"
    _shutdown (threading.py:1583)
Thread 4115152 (idle): "Thread-2"
    wait (threading.py:324)
    run (sisyphus/worker.py:137)
    _bootstrap_inner (threading.py:1038)
    _bootstrap (threading.py:995)
```
This hangs in `_shutdown`, which is an internal Python function, which is called at exit. So it looks like the proc is actually exiting (probably due to the error), but hangs for some reason.

Looking at the `_shutdown` code:
```python
    # Join all non-deamon threads
    while True:
        with _shutdown_locks_lock:
            locks = list(_shutdown_locks)
            _shutdown_locks.clear()

        if not locks:
            break

        for lock in locks:
            # mimic Thread.join()
            lock.acquire()  # <---- line 1583 is here
            lock.release()

        # new threads can be spawned while we were waiting for the other
        # threads to complete
```

So, it waits for a lock.

Looking at `py-spy top`:
```
  3.00%   3.00%    1.04s     1.04s   _shutdown (threading.py)
  0.00%   0.00%   0.060s    0.060s   open_binary (psutil/_common.py)
  0.00%   0.00%   0.030s    0.080s   ppid_map (psutil/_pslinux.py)
  0.00%   0.00%   0.010s    0.020s   _parse_stat_file (psutil/_pslinux.py)
  0.00%   0.00%   0.000s    0.080s   children (psutil/__init__.py)
  0.00%   0.00%   0.000s    0.020s   cpu_times (psutil/_pslinux.py)
  0.00%   0.00%   0.000s    0.010s   bcat (psutil/_common.py)
  0.00%   0.00%   0.000s    0.020s   cpu_percent (psutil/__init__.py)
  0.00%   0.00%   0.000s    0.010s   cat (psutil/_common.py)
  0.00%   0.00%   0.000s    0.100s   get_job_used_resources (sisyphus/engine.py)
  0.00%   0.00%   0.000s    0.100s   _bootstrap (threading.py)
  0.00%   0.00%   0.000s    0.100s   _bootstrap_inner (threading.py)
  0.00%   0.00%   0.000s    0.020s   wrapper (psutil/_common.py)
  0.00%   0.00%   0.000s    0.100s   run (sisyphus/worker.py)
  0.00%   0.00%   0.000s    0.020s   wrapper (psutil/_pslinux.py)
```

So the other thread (`LoggingThread`) is still alive but mostly idles in `self._cond.wait(gs.PLOGGING_INTERVAL)`.

Maybe this is a fork issue?

**Comment by albertz** [comment]
Actually, `worker_helper` has this code:
```python
    ...

    task_id = gs.active_engine.get_task_id(args.task_id)
    logging.debug("Task id: %s" % str(task_id))
    logging_thread = LoggingThread(job, task, task_id)
    logging_thread.start()

    sisyphus.job_path.Path.cacheing_enabled = True
    resume_job = False
    gs.active_engine.init_worker(task)

    # cleanup environment
    if hasattr(task._job, "_sis_environment") and task._job._sis_environment:
        task._job._sis_environment.modify_environment()

    # run task
    task.run(task_id, resume_job, logging_thread=logging_thread)
```
So, if any exception happens here, e.g. in `task.run`, after the `LoggingThread` was created and started, how will that `logging_thread` stop? `logging_thread` is not a daemon thread, so Python will wait for it to finish. The only way to stop it is to call `LoggingThread.stop`. If for some reason, this is not called, the process will hang, as it is the case here.

Looking at `Task.run`, you directly see the issue: Not all possible exceptions there will call `logging_thread.stop()`.

This seems potentially very dangerous to me? I would suggest multiple things:
* Make `LoggingThread` always a daemon thread.
* In the end of `worker_helper`, do this:
```python
try:
    # run task
    task.run(task_id, resume_job, logging_thread=logging_thread)
finally:
    logging_thread.stop()
    logging_thread.join()
```
* The `logging_thread.stop()` calls inside `Task.run` can be cleaned up.

**Comment by albertz** [comment]
Another thing I wonder is that the log file is actually never created. So e.g. I see this:
```
4114998 ?        Ss     0:00 /work/tools/users/zeyer/py-envs/py3.11-torch2.1/bin/python3.11 ./sis worker --engine short work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ create_files 1 --redirect_output
4115002 ?        Sl     1:00  \_ python3 ./sis worker --engine short work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ create_files 1
```
Hanging there as described before.
Now, even if I kill 4115002 here, there is no logfile in `work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ`.
On stdout, I see this from the parent:
```
[2024-01-10 10:45:36,162] ERROR: Main thread unhandled exception: 
EXCEPTION
Traceback (most recent call last):
  File "/u/zeyer/setups/combined/2021-05-31/tools/sisyphus/sisyphus/__main__.py", line 234, in main
    line: args.func(args)
    locals:
      args = <local> Namespace(log_level=20, config_files=[], jobdir='work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ', task_name='create_files', task_id=1, force_resume=False, engine='short', redirect_output=True, func=<function worker at 0x7f894bada980>)
      args.func = <local> <function worker at 0x7f894bada980>
  File "/u/zeyer/setups/combined/2021-05-31/tools/sisyphus/sisyphus/worker.py", line 168, in worker 
    line: worker_helper(args)
    locals:
      worker_helper = <global> <function worker_helper at 0x7f894b97c5e0> 
      args = <local> Namespace(log_level=20, config_files=[], jobdir='work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ', task_name='create_files', task_id=1, force_resume=False, engine='short', redirect_output=True, func=<function worker at 0x7f894bada980>)
  File "/u/zeyer/setups/combined/2021-05-31/tools/sisyphus/sisyphus/worker.py", line 207, in worker_helper 
    line: subprocess.check_call(call, stdout=logfile, stderr=logfile)
    locals:
      subprocess = <global> <module 'subprocess' from '/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py'> 
      subprocess.check_call = <global> <function check_call at 0x7f894c89b420>
      call = <local> ['./sis', 'worker', '--engine', 'short', 'work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ', 'create_files', '1'], len = 7
      stdout = <not found> 
      logfile = <local> <_io.TextIOWrapper name='work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ/log.create_files.1' mode='a' encoding='UTF-8'>
      stderr = <not found>
  File "/work/tools/users/zeyer/linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 413, in check_call 
    line: raise CalledProcessError(retcode, cmd)
    locals:
      CalledProcessError = <global> <class 'subprocess.CalledProcessError'>
      retcode = <local> -15
      cmd = <local> ['./sis', 'worker', '--engine', 'short', 'work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ', 'create_files', '1'], len = 7
CalledProcessError: Command '['./sis', 'worker', '--engine', 'short', 'work/i6_core/returnn/forward/ReturnnForwardJobV2.eGSmwZTLjfgZ', 'create_files', '1']' died with <Signals.SIGTERM: 15>.
```

Ah, I just saw, it was cleared already in the meanwhile, so the logfile was in `ReturnnForwardJobV2.eGSmwZTLjfgZ.cleared.0001`, but still hanging here.
